services:
  - type: web
    name: tamraparni-ayurveda
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn medshop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
