# Generated by Django 4.2.7 on 2025-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum Retail Price', max_digits=10, verbose_name='MRP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
    ]
