# Generated by Django 4.2.7 on 2025-12-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_add_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Maximum Retail Price', max_digits=10, verbose_name='MRP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
    ]
