# Generated by Django 4.2.7 on 2025-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_add_medicine_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether admin has read this message')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of sender', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
