# Generated by Django 4.2.7 on 2025-12-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_mrp_alter_medicine_price'),
        ('medicines', '0005_add_medicine_images'),
    ]

    operations = [
    ]
