# Generated by Django 4.2.7 on 2025-12-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_contactmessage_sitesettings'),
        ('medicines', '0006_merge_20251216_0844'),
    ]

    operations = [
    ]
