# Generated by Django 4.2.7 on 2025-12-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_add_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Video description')),
                ('video_type', models.CharField(choices=[('REEL', 'Reel'), ('PROMO', 'Promotional Video'), ('TESTIMONIAL', 'Customer Testimonial'), ('TUTORIAL', 'Tutorial/How-to'), ('NEWS', 'News/Press'), ('OTHER', 'Other')], default='REEL', max_length=20)),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4 recommended)', null=True, upload_to='media/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Instagram video URL (for embedding)', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image', null=True, upload_to='media/thumbnails/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage or featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Is this video visible on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Video',
                'verbose_name_plural': 'Media Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
