# Generated by Django 4.2.7 on 2025-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(blank=True, help_text='Main website URL for Follow Us section', null=True),
        ),
    ]
