# Generated by Django 4.2.7 on 2026-01-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0011_add_website_url_to_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's email (optional)", max_length=254, null=True)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating from 1-5')),
                ('feedback', models.TextField(blank=True, help_text="Customer's feedback message")),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured testimonials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
