# Generated by Django 4.2.7 on 2026-01-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0012_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's email (optional)", max_length=254, null=True)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating from 1-5')),
                ('feedback', models.TextField(blank=True, help_text="Customer's feedback message")),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to show on product page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Product Feedback',
                'verbose_name_plural': 'Product Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
